package:
    name: cantera
    version: "2.3.0a2"
source:
    git_url: https://github.com/Cantera/cantera.git
    git_tag: master
build:
    number: 1
    string: np{{CONDA_NPY}}py{{CONDA_PY}}_{{PKG_BUILDNUM}}_g{{GIT_FULL_HASH[:7]}}
requirements:
    build:
      - python >=2.7,<3|>=3.3,{{PY_VER}}*
      - numpy >=1.8,{{NPY_VER}}*
      - cython >=0.19*
      - mkl
    run:
      - python {{PY_VER}}*
      - numpy {{NPY_VER}}*
      - mkl
test:
    imports:
      - cantera
about:
    home: http://www.cantera.org
    summary: "Chemical kinetics, thermodynamics, and transport tool suite"
