package:
    name: cantera
    version: "2.3.0a2"
source:
    git_url: https://github.com/Cantera/cantera.git
    git_tag: master
build:
    number: 1
requirements:
    build:
      - python
      - numpy x.x
      - cython
      - mkl
    run:
      - python
      - numpy x.x
      - mkl
test:
    imports:
      - cantera
about:
    home: http://www.cantera.org
    summary: "Chemical kinetics, thermodynamics, and transport tool suite"
