language: cpp
sudo: false
env:
  global:
    secure: "Sj1uxuWdvXbdIxoNVf5OjrDR7EZS9M6mr1dQbEk5wxqvmncsGTh9BAVqvdcPloZZcU/ScrqhfeWBw4vW2UfkYFjlHgRrbEO8/KK29Rk+XW7GtYcoC39fxbX9R7oCljbWajclfm183xLY5TH9JaAR8xmSlWMURJYachoYoY76XVyLD/wCy9YjKIIJ5sndptSFwn7R2tgS7XJDjj6po/PNNukIh6Rl/7AZOWkdtr+F/FhINJkZtn96siqNa6GdOQcxAFnoNRIa5yMeZqNjZtTQoxYDRTlq6dJVffQnRR0xZ5JlDt0mWwt1JSldxwxv6uLbJoBhA76tCLgBhx/nigVFgrS1XJtXEvV6PVr8iLX6Dn4JOvqnmjZgQLkTSFKQT0a5EGzKjWLi3y/tYD91eGcbRnuU7gompsEtatrix8T0xSTuzPzloVgxkNdU9pOoqD/lvGHBGuYqLX3PgnThE38BD4GKwemtD6UF/s0XuYQWQsdqmAAk0Rgoiux7wy1oPwhtOA5/z5Iu82urthAWC05hi+U1+aE+wUCWq/VW4OGfZ5IqKUZhjqlPe9USrCfljCg01/kgh8WwwDVy9Nkrh+k1u6ncdcNKKOCrqOCKlDW8NnHf9HClLYC2IToeOYyK7FhRUPx60/ZW8WwJWHIk9SfwIIJf8imyT2kc5xQKvFVsk7s="
    secure: "RzvO6FC2BAw8lyyMFVCzTjnvC7Bc7Unp/Hl+K3qY76+2l1CgTeNHpL9tkJtgidljA6x2pplgK1+fWyHnFcG6Zq9l3CW++kPy5G/I/DulyCIlMn4CR7CZhcexPlD4ySqSxH/ay4cClIWnqY+evBxC26VlJy2yQiLGPhWLyHPsGY3JOBrJWXs7+zjYPPBussSCSkCLvYq5ICzQFrKIL1AFVu3mp2lslAeLET8cpJIxWUY+fVRZAj5aTA/SGGyH7zikizVSW9vV0yEZVSpdYsf9wsVCpx5tt+eA6iFhXXTKGi+EcKp1Zy6Zq5OsEdnQM/NcSFR7cOtOow6xk451hLg31Mxlts6M/Ck/0IU7HGeDPsdlvLHHaNmt6cVKvX3oy8zhyrf6FeZSpluxYe9vGHl1FMcaDywnm4d5TqKWooinzWnoCizUiUZGqN0VRwvcC/O5yJYLwBzM2XPTUIMML5cAYdTGIJrnheF1D8xBvIEAi0xiNoWy/5eFgoSiV2x+TsEBaB/76ptoq66+u2IkEq47TqYxKduVOIyWjGBKfk2eHkcOlUqbyBwa+PHMWM59XxF9mRmhDN7QBrQFLNZmy68JRl+hM0YH3m1q+E5vVOGjV0crPy2qylOItldSfcZMOPjk/ZXveN238tlZKlTKT88bGvaI6Lmo1SsMkxGgsovD4nc="

addons:
  apt:
    packages:
      - libc6:i386
      - libc6-dev:i386
      - zlib1g:i386
      - gcc-multilib
      - g++-multilib

install:
  - export CONDA_ARCH="${TRAVIS_OS_NAME}_${BUILD_ARCH}"
  - echo $CONDA_ARCH
  - |
    if [[ "$CONDA_ARCH" == "linux_x64" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    elif [[ "$CONDA_ARCH" == "linux_x86" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86.sh -O miniconda.sh;
    elif [[ "$CONDA_ARCH" == "osx_x64" ]]; then
      # Use this line from conda-forge to appropriately set the SDK for clang builds
      # https://github.com/conda-forge/conda-forge-ci-setup-feedstock/blob/53c72da/recipe/run_conda_forge_build_setup_osx#L22
      export MACOSX_DEPLOYMENT_TARGET="10.9"
      export CONDA_BUILD_SYSROOT="$(xcode-select -p)/Platforms/MacOSX.platform/Developer/SDKs/MacOSX${MACOSX_DEPLOYMENT_TARGET}.sdk"
      curl https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -o miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - source $HOME/miniconda/etc/profile.d/conda.sh && conda activate
  - conda config --set always_yes yes --set changeps1 no
  - conda config --append channels conda-forge
  - conda install -q anaconda-client conda-build\<4.0 conda\<5.0 conda-verify\<4.0
  - conda info -a
  - conda list
  # - MW_HEADERS_DIR=$(pwd)/mw_headers
  # - git clone https://cantera:${GIT_PW}@cantera.org/mw_headers.git "${MW_HEADERS_DIR}"
  # - echo $MW_HEADERS_DIR

script:
  - if [ -z "${MATLAB_BUILD}" ]; then
      conda build cantera
    else
      echo conda build cantera-matlab
    fi
  - |
    if [ "${TRAVIS_PULL_REQUEST}" == "false" ] && [ "${TRAVIS_BRANCH}" == "master" ]; then
      anaconda -t $ANACONDA_TOKEN upload --force -l dev $HOME/miniconda/conda-bld/*/cantera*.tar.bz2;
    else
      echo "Nothing was uploaded because this isn't the master branch or it's a pull request.";
    fi

matrix:
  include:
    - os: linux
      env: BUILD_ARCH="x86"
    - os: linux
      env: BUILD_ARCH="x64"
    - os: osx
      env: BUILD_ARCH="x64"
      osx_image: xcode6.4
    - os: linux
      env: BUILD_ARCH="x86" MATLAB_BUILD=1
    - os: linux
      env: BUILD_ARCH="x64" MATLAB_BUILD=1
    - os: osx
      env: BUILD_ARCH="x64" MATLAB_BUILD=1
      osx_image: xcode6.4
