language: cpp
sudo: false
env:
    global:
      secure: "Sj1uxuWdvXbdIxoNVf5OjrDR7EZS9M6mr1dQbEk5wxqvmncsGTh9BAVqvdcPloZZcU/ScrqhfeWBw4vW2UfkYFjlHgRrbEO8/KK29Rk+XW7GtYcoC39fxbX9R7oCljbWajclfm183xLY5TH9JaAR8xmSlWMURJYachoYoY76XVyLD/wCy9YjKIIJ5sndptSFwn7R2tgS7XJDjj6po/PNNukIh6Rl/7AZOWkdtr+F/FhINJkZtn96siqNa6GdOQcxAFnoNRIa5yMeZqNjZtTQoxYDRTlq6dJVffQnRR0xZ5JlDt0mWwt1JSldxwxv6uLbJoBhA76tCLgBhx/nigVFgrS1XJtXEvV6PVr8iLX6Dn4JOvqnmjZgQLkTSFKQT0a5EGzKjWLi3y/tYD91eGcbRnuU7gompsEtatrix8T0xSTuzPzloVgxkNdU9pOoqD/lvGHBGuYqLX3PgnThE38BD4GKwemtD6UF/s0XuYQWQsdqmAAk0Rgoiux7wy1oPwhtOA5/z5Iu82urthAWC05hi+U1+aE+wUCWq/VW4OGfZ5IqKUZhjqlPe9USrCfljCg01/kgh8WwwDVy9Nkrh+k1u6ncdcNKKOCrqOCKlDW8NnHf9HClLYC2IToeOYyK7FhRUPx60/ZW8WwJWHIk9SfwIIJf8imyT2kc5xQKvFVsk7s="

addons:
    apt:
        packages:
          - libc6:i386
          - libc6-dev:i386
          - zlib1g:i386
          - gcc-multilib
          - g++-multilib

install:
  - export CONDA_ARCH="${TRAVIS_OS_NAME}_${BUILD_ARCH}"
  - export PY_MAJ_VER=${BUILD_PYTHON:0:1}
  - |
    if [[ "$CONDA_ARCH" == "linux_x64" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda${PY_MAJ_VER}-latest-Linux-x86_64.sh -O miniconda.sh;
    elif [[ "$CONDA_ARCH" == "linux_x86" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda${PY_MAJ_VER}-latest-Linux-x86.sh -O miniconda.sh;
    elif [[ "$CONDA_ARCH" == "osx_x64" ]]; then
      curl https://repo.continuum.io/miniconda/Miniconda${PY_MAJ_VER}-latest-MacOSX-x86_64.sh -o miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - source $HOME/miniconda/etc/profile.d/conda.sh && conda activate
  - conda config --set always_yes yes --set changeps1 no
  - conda install -q anaconda-client conda-build\<4.0 conda\<5.0
  - conda info -a
  - conda list

script:
  - conda build cantera --python=${BUILD_PYTHON} --numpy=${BUILD_NPY}
  - |
    if [ "${TRAVIS_PULL_REQUEST}" == "false" ] && [ "${TRAVIS_BRANCH}" == "master" ]; then
      anaconda -t $ANACONDA_TOKEN upload --force -l dev $HOME/miniconda/conda-bld/*/cantera*.tar.bz2;
    else
      echo "Nothing was uploaded because this isn't the master branch or it's a pull request.";
    fi

# This matrix section is autogenerated by the generate-build-matrix.py
# file and should not be edited by hand
matrix:
    include:
      - os: linux
        env: BUILD_PYTHON="2.7" BUILD_ARCH="x86" BUILD_NPY="1.13"
      - os: linux
        env: BUILD_PYTHON="2.7" BUILD_ARCH="x86" BUILD_NPY="1.14"
      - os: linux
        env: BUILD_PYTHON="2.7" BUILD_ARCH="x86" BUILD_NPY="1.15"
      - os: linux
        env: BUILD_PYTHON="3.5" BUILD_ARCH="x86" BUILD_NPY="1.13"
      - os: linux
        env: BUILD_PYTHON="3.5" BUILD_ARCH="x86" BUILD_NPY="1.14"
      - os: linux
        env: BUILD_PYTHON="3.5" BUILD_ARCH="x86" BUILD_NPY="1.15"
      - os: linux
        env: BUILD_PYTHON="3.6" BUILD_ARCH="x86" BUILD_NPY="1.13"
      - os: linux
        env: BUILD_PYTHON="3.6" BUILD_ARCH="x86" BUILD_NPY="1.14"
      - os: linux
        env: BUILD_PYTHON="3.6" BUILD_ARCH="x86" BUILD_NPY="1.15"
      - os: linux
        env: BUILD_PYTHON="3.7" BUILD_ARCH="x86" BUILD_NPY="1.14"
      - os: linux
        env: BUILD_PYTHON="3.7" BUILD_ARCH="x86" BUILD_NPY="1.15"
      - os: linux
        env: BUILD_PYTHON="2.7" BUILD_ARCH="x64" BUILD_NPY="1.13"
      - os: linux
        env: BUILD_PYTHON="2.7" BUILD_ARCH="x64" BUILD_NPY="1.14"
      - os: linux
        env: BUILD_PYTHON="2.7" BUILD_ARCH="x64" BUILD_NPY="1.15"
      - os: linux
        env: BUILD_PYTHON="3.5" BUILD_ARCH="x64" BUILD_NPY="1.13"
      - os: linux
        env: BUILD_PYTHON="3.5" BUILD_ARCH="x64" BUILD_NPY="1.14"
      - os: linux
        env: BUILD_PYTHON="3.5" BUILD_ARCH="x64" BUILD_NPY="1.15"
      - os: linux
        env: BUILD_PYTHON="3.6" BUILD_ARCH="x64" BUILD_NPY="1.13"
      - os: linux
        env: BUILD_PYTHON="3.6" BUILD_ARCH="x64" BUILD_NPY="1.14"
      - os: linux
        env: BUILD_PYTHON="3.6" BUILD_ARCH="x64" BUILD_NPY="1.15"
      - os: linux
        env: BUILD_PYTHON="3.7" BUILD_ARCH="x64" BUILD_NPY="1.14"
      - os: linux
        env: BUILD_PYTHON="3.7" BUILD_ARCH="x64" BUILD_NPY="1.15"
      - os: osx
        env: BUILD_PYTHON="2.7" BUILD_ARCH="x64" BUILD_NPY="1.13"
      - os: osx
        env: BUILD_PYTHON="2.7" BUILD_ARCH="x64" BUILD_NPY="1.14"
      - os: osx
        env: BUILD_PYTHON="2.7" BUILD_ARCH="x64" BUILD_NPY="1.15"
      - os: osx
        env: BUILD_PYTHON="3.5" BUILD_ARCH="x64" BUILD_NPY="1.13"
      - os: osx
        env: BUILD_PYTHON="3.5" BUILD_ARCH="x64" BUILD_NPY="1.14"
      - os: osx
        env: BUILD_PYTHON="3.5" BUILD_ARCH="x64" BUILD_NPY="1.15"
      - os: osx
        env: BUILD_PYTHON="3.6" BUILD_ARCH="x64" BUILD_NPY="1.13"
      - os: osx
        env: BUILD_PYTHON="3.6" BUILD_ARCH="x64" BUILD_NPY="1.14"
      - os: osx
        env: BUILD_PYTHON="3.6" BUILD_ARCH="x64" BUILD_NPY="1.15"
      - os: osx
        env: BUILD_PYTHON="3.7" BUILD_ARCH="x64" BUILD_NPY="1.14"
      - os: osx
        env: BUILD_PYTHON="3.7" BUILD_ARCH="x64" BUILD_NPY="1.15"
