version: 1.0.{build}
environment:
  ANACONDA_KEY:
    secure: kiAnoYuLn2aWvx3eXzTZ+qv4sgRiAQIGv54SxfBeket2lYj9VBDyGjYxZ/K2X5Wf

  matrix:
    - PYTHON_LOC: "C:\\Miniconda"
      PYTHON_VERSION: "2.7"
      BUILD_ARCH: "32"

    - PYTHON_LOC: "C:\\Miniconda"
      PYTHON_VERSION: "3.4"
      BUILD_ARCH: "32"

    - PYTHON_LOC: "C:\\Miniconda"
      PYTHON_VERSION: "3.5"
      BUILD_ARCH: "32"

    - PYTHON_LOC: "C:\\Miniconda-x64"
      PYTHON_VERSION: "2.7"
      BUILD_ARCH: "64"

    - PYTHON_LOC: "C:\\Miniconda-x64"
      PYTHON_VERSION: "3.4"
      BUILD_ARCH: "64"

    - PYTHON_LOC: "C:\\Miniconda-x64"
      PYTHON_VERSION: "3.5"
      BUILD_ARCH: "64"

install:
  - cmd: |
      set PATH=%PYTHON_LOC%;%PYTHON_LOC%\Scripts;%PATH%
      call conda install -yq anaconda-client conda=4.2.9 conda-build=2.0.6
      call conda info -a
      call conda list

build_script:
  - cmd: |
      set PATH=%PYTHON_LOC%;%PYTHON_LOC%\Scripts;%PATH%
      call conda build cantera --python=%PYTHON_VERSION% --numpy=1.11

deploy_script:
  - cmd: |
      if "%APPVEYOR_REPO_BRANCH%" == "master" (
        if "%APPVEYOR_PULL_REQUEST_NUMBER%" == "" (
          set PATH=%PYTHON_LOC%;%PYTHON_LOC%\Scripts;%PATH%
          call anaconda -t %ANACONDA_KEY% upload --force -l dev %PYTHON_LOC%\conda-bld\win-%BUILD_ARCH%\cantera*.tar.bz2
        )
      )
