version: 1.0.{build}

install:
  - cmd: set PATH=%PYTHON_LOC%;%PYTHON_LOC%\Scripts;%PATH%
  - cmd: conda install -yq anaconda-client conda^<5.0 conda-build^<4.0
  - cmd: conda info -a
  - cmd: conda list
  - ps: Write-Host $env:APPVEYOR_REPO_BRANCH
  - ps: Write-Host $env:APPVEYOR_PULL_REQUEST_NUMBER

build_script:
  - cmd: set PATH=%PYTHON_LOC%;%PYTHON_LOC%\Scripts;%PATH%
  - cmd: conda build cantera --python=%PYTHON_VERSION% --numpy=%BUILD_NPY%

deploy_script:
  - cmd: set PATH=%PYTHON_LOC%;%PYTHON_LOC%\Scripts;%PATH%
  - ps: |
        if($env:APPVEYOR_REPO_BRANCH -eq "2.4" -and !$env:APPVEYOR_PULL_REQUEST_NUMBER)
        {
          $env:conda_upload = 'true'
        }
        else
        {
          Write-Host "Nothing was uploaded because this isn't the 2.4 branch or it's a pull request."
        }
  - cmd: IF "%conda_upload%"=="true" anaconda -t %ANACONDA_KEY% upload "%PYTHON_LOC%\conda-bld\win-%BUILD_ARCH%\cantera*.tar.bz2"

environment:
    ANACONDA_KEY:
        secure: LOVYRtf8/xutoHoymzsYG2FSt7fkaI3VAcbVHyrWndF7FK3gA6Ua/1xhiyIFtr0e

    # This matrix section is autogenerated by the generate-build-matrix.py
    # file and should not be edited by hand
    matrix:
      - PYTHON_LOC: C:\Miniconda
        PYTHON_VERSION: '2.7'
        BUILD_ARCH: '32'
        BUILD_NPY: '1.13'
      - PYTHON_LOC: C:\Miniconda
        PYTHON_VERSION: '2.7'
        BUILD_ARCH: '32'
        BUILD_NPY: '1.14'
      - PYTHON_LOC: C:\Miniconda
        PYTHON_VERSION: '2.7'
        BUILD_ARCH: '32'
        BUILD_NPY: '1.15'
      - PYTHON_LOC: C:\Miniconda35
        PYTHON_VERSION: '3.5'
        BUILD_ARCH: '32'
        BUILD_NPY: '1.13'
      - PYTHON_LOC: C:\Miniconda35
        PYTHON_VERSION: '3.5'
        BUILD_ARCH: '32'
        BUILD_NPY: '1.14'
      - PYTHON_LOC: C:\Miniconda35
        PYTHON_VERSION: '3.5'
        BUILD_ARCH: '32'
        BUILD_NPY: '1.15'
      - PYTHON_LOC: C:\Miniconda36
        PYTHON_VERSION: '3.6'
        BUILD_ARCH: '32'
        BUILD_NPY: '1.13'
      - PYTHON_LOC: C:\Miniconda36
        PYTHON_VERSION: '3.6'
        BUILD_ARCH: '32'
        BUILD_NPY: '1.14'
      - PYTHON_LOC: C:\Miniconda36
        PYTHON_VERSION: '3.6'
        BUILD_ARCH: '32'
        BUILD_NPY: '1.15'
      - PYTHON_LOC: C:\Miniconda36
        PYTHON_VERSION: '3.7'
        BUILD_ARCH: '32'
        BUILD_NPY: '1.14'
      - PYTHON_LOC: C:\Miniconda36
        PYTHON_VERSION: '3.7'
        BUILD_ARCH: '32'
        BUILD_NPY: '1.15'
      - PYTHON_LOC: C:\Miniconda-x64
        PYTHON_VERSION: '2.7'
        BUILD_ARCH: '64'
        BUILD_NPY: '1.13'
      - PYTHON_LOC: C:\Miniconda-x64
        PYTHON_VERSION: '2.7'
        BUILD_ARCH: '64'
        BUILD_NPY: '1.14'
      - PYTHON_LOC: C:\Miniconda-x64
        PYTHON_VERSION: '2.7'
        BUILD_ARCH: '64'
        BUILD_NPY: '1.15'
      - PYTHON_LOC: C:\Miniconda35-x64
        PYTHON_VERSION: '3.5'
        BUILD_ARCH: '64'
        BUILD_NPY: '1.13'
      - PYTHON_LOC: C:\Miniconda35-x64
        PYTHON_VERSION: '3.5'
        BUILD_ARCH: '64'
        BUILD_NPY: '1.14'
      - PYTHON_LOC: C:\Miniconda35-x64
        PYTHON_VERSION: '3.5'
        BUILD_ARCH: '64'
        BUILD_NPY: '1.15'
      - PYTHON_LOC: C:\Miniconda36-x64
        PYTHON_VERSION: '3.6'
        BUILD_ARCH: '64'
        BUILD_NPY: '1.13'
      - PYTHON_LOC: C:\Miniconda36-x64
        PYTHON_VERSION: '3.6'
        BUILD_ARCH: '64'
        BUILD_NPY: '1.14'
      - PYTHON_LOC: C:\Miniconda36-x64
        PYTHON_VERSION: '3.6'
        BUILD_ARCH: '64'
        BUILD_NPY: '1.15'
      - PYTHON_LOC: C:\Miniconda36-x64
        PYTHON_VERSION: '3.7'
        BUILD_ARCH: '64'
        BUILD_NPY: '1.14'
      - PYTHON_LOC: C:\Miniconda36-x64
        PYTHON_VERSION: '3.7'
        BUILD_ARCH: '64'
        BUILD_NPY: '1.15'
