version: 1.0.{build}
environment:
  ANACONDA_KEY:
    secure: kiAnoYuLn2aWvx3eXzTZ+qv4sgRiAQIGv54SxfBeket2lYj9VBDyGjYxZ/K2X5Wf

install:
  - cmd: |
      set ORIGPATH=%PATH%
      set PATH=C:\Miniconda;C:\Miniconda\Scripts;%ORIGPATH%
      call conda install -y anaconda-client conda-build
      set PATH=C:\Miniconda-x64;C:\Miniconda-x64\Scripts;%ORIGPATH%
      call conda install -y anaconda-client conda-build

build_script:
  - cmd: |
      set PATH=C:\Miniconda;C:\Miniconda\Scripts;%ORIGPATH%
      call conda build cantera --python=2.7 --numpy=1.11
      call conda build cantera --python=3.4 --numpy=1.11
      call conda build cantera --python=3.5 --numpy=1.11
      set PATH=C:\Miniconda-x64;C:\Miniconda-x64\Scripts;%ORIGPATH%
      call conda build cantera --python=2.7 --numpy=1.11
      call conda build cantera --python=3.4 --numpy=1.11
      call conda build cantera --python=3.5 --numpy=1.11

deploy_script:
  - cmd: |
      set PATH=C:\Miniconda;C:\Miniconda\Scripts;%ORIGPATH%
      call anaconda -t %ANACONDA_KEY% upload --force -l dev C:\Miniconda\conda-bld\win-32\cantera*.tar.bz2
      set PATH=C:\Miniconda-x64;C:\Miniconda-x64\Scripts;%ORIGPATH%
      call anaconda -t %ANACONDA_KEY% upload --force -l dev C:\Miniconda-x64\conda-bld\win-64\cantera*.tar.bz2
