version: 1.0.{build}
environment:
  ANACONDA_KEY:
    secure: kiAnoYuLn2aWvx3eXzTZ+qv4sgRiAQIGv54SxfBeket2lYj9VBDyGjYxZ/K2X5Wf

  matrix:
    - PYTHON_LOC: "C:\\Miniconda"
      PYTHON_VERSION: "2.7"
      BUILD_ARCH: "32"

    - PYTHON_LOC: "C:\\Miniconda"
      PYTHON_VERSION: "3.4"
      BUILD_ARCH: "32"

    - PYTHON_LOC: "C:\\Miniconda"
      PYTHON_VERSION: "3.5"
      BUILD_ARCH: "32"

    - PYTHON_LOC: "C:\\Miniconda-x64"
      PYTHON_VERSION: "2.7"
      BUILD_ARCH: "64"

    - PYTHON_LOC: "C:\\Miniconda-x64"
      PYTHON_VERSION: "3.4"
      BUILD_ARCH: "64"

    - PYTHON_LOC: "C:\\Miniconda-x64"
      PYTHON_VERSION: "3.5"
      BUILD_ARCH: "64"

install:
  - cmd: set PATH=%PYTHON_LOC%;%PYTHON_LOC%\Scripts;%PATH%
  - cmd: conda install -yq anaconda-client conda=4.2.9 conda-build=2.0.6
  - cmd: conda info -a
  - cmd: conda list
  - ps: Write-Host $env:APPVEYOR_REPO_BRANCH
  - ps: Write-Host $env:APPVEYOR_PULL_REQUEST_NUMBER

build_script:
  - cmd: set PATH=%PYTHON_LOC%;%PYTHON_LOC%\Scripts;%PATH%
  - cmd: conda build cantera --python=%PYTHON_VERSION% --numpy=1.11

deploy_script:
  - cmd: set PATH=%PYTHON_LOC%;%PYTHON_LOC%\Scripts;%PATH%
  - ps: >-
      if($env:APPVEYOR_REPO_BRANCH -eq "master" -and !$env:APPVEYOR_PULL_REQUEST_NUMBER)
      {
        anaconda -t $env:ANACONDA_KEY upload --force -l dev "$env:PYTHON_LOC\conda-bld\win-$env:BUILD_ARCH\cantera*.tar.bz2" 2>&1 | %{ "$_" }
      }
      else
      {
        Write-Host "Nothing was uploaded because this isn't the master branch or it's a pull request."
      }
