version: 1.0.{build}

install:
  - cmd: set PATH=%PYTHON_LOC%;%PYTHON_LOC%\Scripts;%PATH%
  - cmd: conda install -yq anaconda-client conda-build=3.0.6 conda=4.3.22
  - cmd: conda info -a
  - cmd: conda list
  - ps: Write-Host $env:APPVEYOR_REPO_BRANCH
  - ps: Write-Host $env:APPVEYOR_PULL_REQUEST_NUMBER

build_script:
  - cmd: set PATH=%PYTHON_LOC%;%PYTHON_LOC%\Scripts;%PATH%
  - cmd: conda build cantera --python=%PYTHON_VERSION% --numpy=%BUILD_NPY%

deploy_script:
  - cmd: set PATH=%PYTHON_LOC%;%PYTHON_LOC%\Scripts;%PATH%
  - ps: |
        if($env:APPVEYOR_REPO_BRANCH -eq "master" -and !$env:APPVEYOR_PULL_REQUEST_NUMBER)
        {
          $env:conda_upload = 'true'
        }
        else
        {
          Write-Host "Nothing was uploaded because this isn't the master branch or it's a pull request."
        }
  - cmd: IF "%conda_upload%"=="true" anaconda -t %ANACONDA_KEY% upload --force -l dev "%PYTHON_LOC%\conda-bld\win-%BUILD_ARCH%\cantera*.tar.bz2"

environment:
    ANACONDA_KEY:
        secure: kiAnoYuLn2aWvx3eXzTZ+qv4sgRiAQIGv54SxfBeket2lYj9VBDyGjYxZ/K2X5Wf

    # This matrix section is autogenerated by the generate-build-matrix.py
    # file and should not be edited by hand
    matrix:
      - PYTHON_LOC: C:\Miniconda
        PYTHON_VERSION: '2.7'
        BUILD_ARCH: '32'
        BUILD_NPY: '1.12'
      - PYTHON_LOC: C:\Miniconda
        PYTHON_VERSION: '2.7'
        BUILD_ARCH: '32'
        BUILD_NPY: '1.13'
      - PYTHON_LOC: C:\Miniconda
        PYTHON_VERSION: '3.5'
        BUILD_ARCH: '32'
        BUILD_NPY: '1.12'
      - PYTHON_LOC: C:\Miniconda
        PYTHON_VERSION: '3.5'
        BUILD_ARCH: '32'
        BUILD_NPY: '1.13'
      - PYTHON_LOC: C:\Miniconda
        PYTHON_VERSION: '3.6'
        BUILD_ARCH: '32'
        BUILD_NPY: '1.12'
      - PYTHON_LOC: C:\Miniconda
        PYTHON_VERSION: '3.6'
        BUILD_ARCH: '32'
        BUILD_NPY: '1.13'
      - PYTHON_LOC: C:\Miniconda-x64
        PYTHON_VERSION: '2.7'
        BUILD_ARCH: '64'
        BUILD_NPY: '1.12'
      - PYTHON_LOC: C:\Miniconda-x64
        PYTHON_VERSION: '2.7'
        BUILD_ARCH: '64'
        BUILD_NPY: '1.13'
      - PYTHON_LOC: C:\Miniconda-x64
        PYTHON_VERSION: '3.5'
        BUILD_ARCH: '64'
        BUILD_NPY: '1.12'
      - PYTHON_LOC: C:\Miniconda-x64
        PYTHON_VERSION: '3.5'
        BUILD_ARCH: '64'
        BUILD_NPY: '1.13'
      - PYTHON_LOC: C:\Miniconda-x64
        PYTHON_VERSION: '3.6'
        BUILD_ARCH: '64'
        BUILD_NPY: '1.12'
      - PYTHON_LOC: C:\Miniconda-x64
        PYTHON_VERSION: '3.6'
        BUILD_ARCH: '64'
        BUILD_NPY: '1.13'
