version: 1.0.{build}
image: Visual Studio 2017

install:
  - cmd: CALL %PYTHON_LOC%\Scripts\activate.bat
  - cmd: conda install -yq anaconda-client conda^<5.0 conda-build^<4.0 conda-verify^<4.0
  - cmd: conda info -a
  - cmd: conda list
  - cmd: IF "%MATLAB_BUILD%"=="1" SET "MW_HEADERS_DIR=%CD%\..\mw_headers"
  - cmd: IF "%MATLAB_BUILD%"=="1" git clone https://cantera:%GIT_PW%@cantera.org/mw_headers.git "%MW_HEADERS_DIR%"
  - ps: Write-Host $env:APPVEYOR_REPO_BRANCH
  - ps: Write-Host $env:APPVEYOR_PULL_REQUEST_NUMBER

build_script:
  - cmd: IF "%MATLAB_BUILD%"=="0" conda build cantera -m .\.ci_support\conda_build_config.yaml
  - cmd: IF "%MATLAB_BUILD%"=="1" conda build cantera-matlab -m .\.ci_support\conda_build_config.yaml

deploy_script:
  - ps: |
        if($env:APPVEYOR_REPO_BRANCH -eq "master" -and !$env:APPVEYOR_PULL_REQUEST_NUMBER)
        {
          $env:conda_upload = 'true'
        }
        else
        {
          Write-Host "Nothing was uploaded because this isn't the master branch or it's a pull request."
        }
  - cmd: IF "%conda_upload%"=="true" anaconda -t %ANACONDA_KEY% upload --force -l dev "%PYTHON_LOC%\conda-bld\win-%BUILD_ARCH%\cantera*.tar.bz2"

environment:
  ANACONDA_KEY:
    secure: LOVYRtf8/xutoHoymzsYG2FSt7fkaI3VAcbVHyrWndF7FK3gA6Ua/1xhiyIFtr0e
  GIT_PW:
    secure: ZDKGbBpWbzWubzWcf909xg==

  matrix:
    - PYTHON_LOC: C:\Miniconda3
      BUILD_ARCH: '32'
      MATLAB_BUILD: '0'
    - PYTHON_LOC: C:\Miniconda3-x64
      BUILD_ARCH: '64'
      MATLAB_BUILD: '0'
    - PYTHON_LOC: C:\Miniconda3
      BUILD_ARCH: '32'
      MATLAB_BUILD: '1'
    - PYTHON_LOC: C:\Miniconda3-x64
      BUILD_ARCH: '64'
      MATLAB_BUILD: '1'
