version: 1.0.{build}

install:
  - cmd: set PATH=%PYTHON_LOC%;%PYTHON_LOC%\Scripts;%PATH%
  - cmd: conda install -yq anaconda-client conda^<5.0 conda-build^<4.0 conda-verify^<4.0
  - cmd: conda info -a
  - cmd: conda list
  - ps: Write-Host $env:APPVEYOR_REPO_BRANCH
  - ps: Write-Host $env:APPVEYOR_PULL_REQUEST_NUMBER

build_script:
  - cmd: set PATH=%PYTHON_LOC%;%PYTHON_LOC%\Scripts;%PATH%
  - cmd: conda build cantera

deploy_script:
  - cmd: set PATH=%PYTHON_LOC%;%PYTHON_LOC%\Scripts;%PATH%
  - ps: |
        if($env:APPVEYOR_REPO_BRANCH -eq "master" -and !$env:APPVEYOR_PULL_REQUEST_NUMBER)
        {
          $env:conda_upload = 'true'
        }
        else
        {
          Write-Host "Nothing was uploaded because this isn't the master branch or it's a pull request."
        }
  - cmd: IF "%conda_upload%"=="true" anaconda -t %ANACONDA_KEY% upload --force -l dev "%PYTHON_LOC%\conda-bld\win-%BUILD_ARCH%\cantera*.tar.bz2"

environment:
    ANACONDA_KEY:
        secure: LOVYRtf8/xutoHoymzsYG2FSt7fkaI3VAcbVHyrWndF7FK3gA6Ua/1xhiyIFtr0e

    matrix:
      - PYTHON_LOC: C:\Miniconda3
        BUILD_ARCH: '32'
      - PYTHON_LOC: C:\Miniconda3-x64
        BUILD_ARCH: '64'
