{% set data = load_file_regex(load_file='SConstruct', regex_pattern="env\\[.cantera_version.\\] = .([\d.abrc]+).") %}
{% set version = data.group(1) %}

package:
  name: cantera-recipe
  version: {{ version }}

source:
  git_url: https://github.com/Cantera/cantera.git
  git_tag: {{ environ.get('INCOMING_REF', 'main').replace('refs/heads/', '') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - scons >=4.1
  host:
    - libboost
    - openblas  # [osx]
    # - mkl  # [linux] # TODO: reactivate MKL in permanent fix of #29
    - pywin32  # [win]

build:
  number: 0
  include_recipe: True

outputs:
  - name: libcantera-devel
    script: build_devel.sh  # [not win]
    script: build_devel.bat  # [win]

    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        # At the moment, the toolchain does not provide Fortran for Windows
        - {{ compiler('fortran') }}  # [not win]
        - scons >=4.1
        - cython
      host:
        - python {{ python }}
        - libboost
        - openblas  # [osx]
        # - mkl  # [linux] # TODO: reactivate MKL in permanent fix of #29
        - numpy
        - pywin32  # [win]
      run:
        - libboost

  - name: cantera
    script: build_py.sh  # [not win]
    script: build_py.bat  # [win]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - scons >=4.1
      host:
        - pip
        - setuptools
        - libboost
        - openblas  # [osx]
        # - mkl  # [linux] # TODO: reactivate MKL in permanent fix of #29
        - pywin32  # [win]
        # This is added here so conda-build doesn't package it
        - libcantera-devel {{ version }}
      run:
        - python
        - setuptools
        - {{ pin_compatible('numpy') }}
        - h5py
        - ruamel.yaml
        - openblas  # [osx]
        # - mkl  # [linux] # TODO: reactivate MKL in permanent fix of #29
    build:
      entry_points:
        - ck2yaml = cantera.ck2yaml:script_entry_point
        - cti2yaml = cantera.cti2yaml:main
        - ctml2yaml = cantera.ctml2yaml:main
        - yaml2ck = cantera.yaml2ck:main
      include_recipe: True
      ignore_run_exports_from:
        # only the header part of these libraries are used
        - libboost
        - python
    test:
      requires:
        - pytest
      imports:
        - cantera
      source_files:
        - test/python
        - test/data
        - data
      commands:
        - pytest -vv test/python
        - cti2yaml --help
        - ck2yaml --help
        - ctml2yaml --help
        - yaml2ck --help
        - man ck2yaml  # [not win]
        - man cti2yaml  # [not win]
        - man ctml2yaml  # [not win]
        - man yaml2ck  # [not win]

about:
  home: https://cantera.org
  summary: "Chemical kinetics, thermodynamics, and transport tool suite"
  license: BSD-3-Clause
  license_family: BSD
  license_file: License.txt
  dev_url: https://github.com/cantera/cantera
  description: >
    Cantera is an open-source suite of tools for problems involving chemical kinetics,
    thermodynamics, and transport processes
  doc_url: https://cantera.org/documentation
