{% set data = load_file_regex(load_file='SConstruct', regex_pattern="env\\['cantera_version'\\] = .([\d.abrc]+).") %}

package:
    name: cantera
    version: {{ data.group(1) }}
source:
    git_url: https://github.com/Cantera/cantera.git
    git_tag: master
build:
    number: 4
    string: np{{CONDA_NPY}}py{{CONDA_PY}}_{{PKG_BUILDNUM}}_g{{GIT_FULL_HASH[:7]}}
    script_env:
      - CONDA_ARCH
requirements:
    build:
      - python >=2.7,<3|>=3.3,{{PY_VER}}*
      - numpy >=1.8,{{NPY_VER}}*
      - cython >=0.23*
      - mkl # [not win]
    run:
      - python {{PY_VER}}*
      - numpy {{NPY_VER}}*
      - mkl # [not win]
      - vs2015_runtime # [win]
test:
    imports:
      - cantera
    commands:
      - python -m unittest -v cantera.test
about:
    home: http://www.cantera.org
    summary: "Chemical kinetics, thermodynamics, and transport tool suite"
