{% set data = load_file_regex(load_file='SConstruct', regex_pattern="env\\['cantera_version'\\] = .([\d.abrc]+).") %}

package:
    name: cantera
    version: {{ data.group(1) }}
source:
    git_url: https://github.com/Cantera/cantera.git
    git_tag: master
build:
    number: 0
    string: np{{CONDA_NPY}}py{{CONDA_PY}}_{{PKG_BUILDNUM}}
    script_env:
      - CONDA_ARCH
    entry_points:
      - ck2cti = cantera.ck2cti:script_entry_point
      - ctml_writer = cantera.ctml_writer:main
requirements:
    build:
      - python >=2.7,<3|>=3.3,{{PY_VER}}*
      - numpy >=1.8.1,{{NPY_VER}}*
      - boost
      - mkl # [linux]
      - cython >=0.23
      - pywin32 # [win]
    run:
      - python {{PY_VER}}*
      - numpy {{NPY_VER}}*
      - mkl # [linux]
      - vs2015_runtime # [win]
test:
    imports:
      - cantera
    commands:
      - python -m unittest -v cantera.test
about:
  home: https://cantera.org
  summary: "Chemical kinetics, thermodynamics, and transport tool suite"
  license: BSD-3-Clause
  license_family: BSD
  license_file: License.txt
  dev_url: https://github.com/cantera/cantera
  description: Cantera is an open-source suite of tools for problems involving chemical kinetics, thermodynamics, and transport processes
  doc_url: https://cantera.org/documentation
  dev_url: https://github.com/Cantera/cantera
