{% set data = load_file_regex(load_file='SConstruct', regex_pattern="env\\['cantera_version'\\] = .([\d.abrc]+).") %}

package:
  name: cantera-recipe
  version: {{ data.group(1) }}

source:
  git_url: https://github.com/Cantera/cantera.git
  git_tag: master

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - scons >=3.0
  host:
    - libboost
    - mkl  # [linux]

build:
  number: 0
  include_recipe: True

outputs:
  - name: libcantera
    script: build_lib.sh  # [not win]
    script: build_lib.bat  # [win]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - scons >=3.0
      host:
        - libboost
        - mkl  # [linux]
      run:
        - mkl  # [linux]
    build:
      include_recipe: True

  - name: cantera
    script: build_py.sh  # [not win]
    script: build_py.bat  # [win]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - scons >=3.0
      host:
        - python
        - libboost
        - mkl  # [linux]
        - numpy
        - cython
      run:
        - python
        - {{ pin_compatible('numpy') }}
        - mkl  # [linux]
        - vs2015_runtime  # [win]
    build:
      entry_points:
        - ck2cti = cantera.ck2cti:script_entry_point
        - ctml_writer = cantera.ctml_writer:main
      include_recipe: True
    test:
      imports:
        - cantera
      commands:
        - python -m unittest -v cantera.test
        - ck2cti --help

about:
  home: https://cantera.org
  summary: "Chemical kinetics, thermodynamics, and transport tool suite"
  license: BSD-3-Clause
  license_family: BSD
  license_file: License.txt
  dev_url: https://github.com/cantera/cantera
  description: Cantera is an open-source suite of tools for problems involving chemical kinetics, thermodynamics, and transport processes
  doc_url: https://cantera.org/documentation
  dev_url: https://github.com/Cantera/cantera
