{% set data = load_file_regex(load_file='SConstruct', regex_pattern="env\\['cantera_version'\\] = .([\d.abrc]+).") %}

package:
    name: cantera
    version: {{ data.group(1) }}
source:
    git_url: https://github.com/Cantera/cantera.git
    git_tag: v2.3.0
    patches:
      - XFail-test-on-OSX-with-MKL.patch  # [osx]
build:
    number: 1
    string: np{{CONDA_NPY}}py{{CONDA_PY}}_{{PKG_BUILDNUM}}
    script_env:
      - CONDA_ARCH
    entry_points:
      - ck2cti = cantera.ck2cti:script_entry_point
      - ctml_writer = cantera.ctml_writer:main
      - mixmaster = cantera.mixmaster.__main__:main
requirements:
    build:
      - python >=2.7,<3|>=3.3,{{PY_VER}}*
      - numpy >=1.8,{{NPY_VER}}*
      - mkl # [not win]
    run:
      - python {{PY_VER}}*
      - numpy {{NPY_VER}}*
      - mkl # [not win]
      - vs2015_runtime # [win]
test:
    imports:
      - cantera
    commands:
      - python -m unittest -v cantera.test
about:
    home: http://www.cantera.org
    summary: "Chemical kinetics, thermodynamics, and transport tool suite"
