python:
  - '3.7'
  - '3.8'
  - '3.9'
  - '3.10'
numpy:
  - '1.16'
  - '1.16'
  - '1.19'
  - '1.21'
zip_keys:
- - python
  - numpy
macos_machine:                 # [osx]
  - x86_64-apple-darwin13.4.0  # [osx]
MACOSX_DEPLOYMENT_TARGET:      # [osx]
  - '10.15'                    # [osx]
