python:
  - '3.6'
  - '3.7'
  - '3.8'
  - '3.9'
numpy:
  - '1.16'
  - '1.16'
  - '1.16'
  - '1.19'
zip_keys:
- - python
  - numpy
macos_min_version:             # [osx]
  - '10.9'                     # [osx]
macos_machine:                 # [osx]
  - x86_64-apple-darwin13.4.0  # [osx]
MACOSX_DEPLOYMENT_TARGET:      # [osx]
  - '10.9'                     # [osx]
cxx_compiler:                  # [win]
  - vs2017                     # [win]
c_compiler:                    # [win]
  - vs2017                     # [win]
vc:                            # [win]
  - '14.1'                     # [win]
