{% set data = load_file_regex(load_file='SConstruct', regex_pattern="env\\['cantera_version'\\] = .([\d.abrc]+).") %}

package:
  name: cantera-matlab
  version: {{ data.group(1) }}

source:
  git_url: https://github.com/Cantera/cantera.git
  git_tag: 'v2.5.0b1'

requirements:
  build:
    - {{ compiler('c') }}  # [not win]
    - {{ compiler('cxx') }}  # [not win]
    - vs2017_win-64 ==19.15.*  # [win64]
    - vs2017_win-32 ==19.15.*  # [win32]
    - scons >=3.1
    - python >=3.5
    - numpy
  host:
    - libboost
  run:
    - vs2015_runtime  # [win]

build:
  number: 0
  include_recipe: True
  script_env:
    - MW_HEADERS_DIR

about:
  home: https://cantera.org
  summary: "Chemical kinetics, thermodynamics, and transport tool suite"
  license: BSD-3-Clause
  license_family: BSD
  license_file: License.txt
  dev_url: https://github.com/cantera/cantera
  description: Cantera is an open-source suite of tools for problems involving chemical kinetics, thermodynamics, and transport processes
  doc_url: https://cantera.org/documentation
