{% set data = load_file_regex(load_file='SConstruct', regex_pattern="env\\[.cantera_version.\\] = .([\d.abrc]+).") %}

package:
  name: cantera-matlab
  version: {{ data.group(1) }}

source:
  git_url: {{ environ.get('CANTERA_GIT', 'https://github.com/Cantera/cantera.git') }}
  git_tag: {{ environ.get('INCOMING_REF', 'main').replace('refs/heads/', '') }}

requirements:
  build:
    - scons >=3.1  # [not win]
    - scons >=4.1  # [win]
  host:
    - libboost
    - pywin32  # [win]
    - hdf5

build:
  number: 0
  include_recipe: True
  script_env:
    - MW_HEADERS_DIR
  ignore_run_exports_from:
    # Only the header version of this library is used
    - libboost

about:
  home: https://cantera.org
  summary: "Chemical kinetics, thermodynamics, and transport tool suite"
  license: BSD-3-Clause
  license_family: BSD
  license_file: License.txt
  dev_url: https://github.com/cantera/cantera
  description: Cantera is an open-source suite of tools for problems involving chemical kinetics, thermodynamics, and transport processes
  doc_url: https://cantera.org/documentation
