name: CI

on:
  push:
    # Build on tags that look like releases
    tags:
      - v*
    # Build when main is pushed to
    branches:
      - main
  pull_request:
    # Build when a pull request targets main
    branches:
      - main
  workflow_dispatch:

env:
  MW_HEADERS_DIR: ${{ github.workspace }}/../mw_headers
  MACOSX_DEPLOYMENT_TARGET: "10.9"

jobs:
  build:
    name: ${{ matrix.os }} with MATLAB=${{ matrix.MATLAB }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        MATLAB: [0, 1]
        os: [windows-2016, ubuntu-latest, macos-latest]
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - name: Set Up macOS
      if: runner.os == 'macOS'
      run: echo "CONDA_BUILD_SYSROOT=$(xcode-select -p)/Platforms/MacOSX.platform/Developer/SDKs/MacOSX${MACOSX_DEPLOYMENT_TARGET}.sdk" >> $GITHUB_ENV
    - name: Install macOS SDK
      if: runner.os == 'macOS'
      run: |
        curl -L -O https://github.com/phracker/MacOSX-SDKs/releases/download/10.15/MacOSX${MACOSX_DEPLOYMENT_TARGET}.sdk.tar.xz
        tar -xf MacOSX${MACOSX_DEPLOYMENT_TARGET}.sdk.tar.xz -C "$(dirname "$CONDA_BUILD_SYSROOT")"
        # set minimum sdk version to our target
        plutil -replace MinimumSDKVersion -string ${MACOSX_DEPLOYMENT_TARGET} $(xcode-select -p)/Platforms/MacOSX.platform/Info.plist
        plutil -replace DTSDKName -string macosx${MACOSX_DEPLOYMENT_TARGET}internal $(xcode-select -p)/Platforms/MacOSX.platform/Info.plist
    - name: Append to conda build config
      if: runner.os == 'macOS'
      run: |
        echo "
        CONDA_BUILD_SYSROOT:
        - ${CONDA_BUILD_SYSROOT}
        " >> ./.ci_support/conda_build_config.yaml;
        echo "
        numpy:
        - 1.11
        " >> ${HOME}/conda_build_config.yaml;
    - name: Set Up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        conda-build-version: '3.21'
        activate-environment: ''
        auto-activate-base: true
    - name: Install Conda dependencies
      shell: bash -l {0}
      run: conda install -q anaconda-client conda-verify\<4.0 ripgrep
    - name: Build the Python and libcantera recipe
      shell: bash -l {0}
      run: conda build ./cantera -m ./.ci_support/conda_build_config.yaml
      if: matrix.MATLAB == 0
    # The known_hosts key is generated with `ssh-keygen -F cantera.org` from a
    # machine that has previously logged in to cantera.org and trusts
    # that it logged in to the right machine
    - name: Set up SSH key and host for deploy
      if: matrix.MATLAB == 1
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.CTDEPLOY_SSH_KEY }}
        known_hosts: ${{ secrets.CTDEPLOY_KNOWN_HOSTS }}
    - name: Install rsync on Windows
      if: matrix.MATLAB == 1 && runner.os == 'Windows'
      run: choco install rsync
    - name: Display the path
      run: |
        import os
        from pathlib import Path, PurePosixPath
        print(os.environ["MW_HEADERS_DIR"])
        mw_headers_dir = Path(os.environ["MW_HEADERS_DIR"])
        mw_headers_dir = PurePosixPath(
            "/cygdrive",
            mw_headers_dir.drive[0],
            PurePosixPath(*mw_headers_dir.parts[1:])
        )
        with Path(os.environ["GITHUB_ENV"]).open(mode="a") as gh_env:
            gh_env.write(f"MW_HEADERS_DIR={mw_headers_dir}")
        print(mw_headers_dir)
      shell: python
      if: runner.os == 'Windows' && matrix.MATLAB == 1
    - name: Get the MATLAB headers
      if: matrix.MATLAB == 1
      run: "rsync -azvP ctdeploy@cantera.org:. ${MW_HEADERS_DIR}"
      shell: bash -l {0}
    - name: Build the MATLAB recipe
      shell: bash -l {0}
      run: conda build ./cantera-matlab -m ./.ci_support/conda_build_config.yaml
      if: matrix.MATLAB == 1
    - name: Upload package to anaconda.org
      run: |
        anaconda --token ${{ secrets.ANACONDA_TOKEN }} upload --force --label dev $CONDA/conda-bld/*/*cantera*.tar.bz2
      shell: bash -l {0}
      if: github.event_name == 'push' && github.event.ref == 'refs/heads/main'
